[package]
name = "mobius"
version = "0.1.0"
edition = "2024"

[dependencies]
keter = { path = "../sefirot/keter", features = ["trace"] }
keter_testbed = { path = "../sefirot/testbed", features = ["video"] }
